# Generated by Django 4.2.16 on 2025-10-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0292_giftcard_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="allow_position_cancel",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="item",
            name="allow_position_change",
            field=models.BooleanField(default=True),
        ),
    ]
